### ISSUE TITLE
Processing provided DSL script takes so long

### ISSUE THREAD

**Issue by elmodeer** [uhafner/warnings-ng-plugin-devenv#19]
the Processing provided DSL script step in the docker image takes around 20 Mins to complete. is this normal ?? what can I do to mitigate this effect as it hinders the development tremendously.

here is an example from the logs
`jenkins-controller_1  | 2022-02-20 **21:26:24.916+0000** [id=47]    WARNING i.j.p.casc.BaseConfigurator#createAttribute: Can't handle class javaposse.jobdsl.plugin.GlobalJobDslSecurityConfiguration#metaClass: type is abstract but not Describable.
jenkins-controller_1  | Processing provided DSL script

jenkins-controller_1  | 2022-02-20 **21:43:01.714+0000** [id=47]    INFO    j.j.plugin.JenkinsJobManagement#createOrUpdateConfig: createOrUpdateConfig for pipeline-codingstyle`

**Comment by uhafner** [comment]
I reported the bug quite some time ago, but the Job DSL plugin is not maintained anymore: 
https://issues.jenkins.io/browse/JENKINS-60125

What I am doing: after the first initialization that created the jobs remove everything of the jobs section from the file
`docker/volumes/jenkins-home/jenkins.yml`
(see original file https://github.com/uhafner/warnings-ng-plugin-devenv/blob/main/docker/images/jenkins-controller/jenkins.yaml#L156-L292)

**Comment by uhafner** [comment]
Workaround described by https://github.com/uhafner/warnings-ng-plugin-devenv/commit/69592374ba95654c4c40bda4a54a1f1c83386d4e
