### ISSUE TITLE
Could not start the provided jobs

### ISSUE THREAD

**Issue by XiongKezhi** [uhafner/warnings-ng-plugin-devenv#6]
I have successfully set up the environment following the [Installation Step](https://github.com/uhafner/warnings-ng-plugin-devenv#installation-steps) and everything looks fine. After I login in the Jenkins, there are 5 five jobs listing, but I just cannot start any job or trigger a build action using the 'build now' bottom as I do before using Jenkins, because there is no such a bottom in the side-panel.  It just shows me a no workspace error like this:

![2020-02-15 12-45-56 的屏幕截图](https://user-images.githubusercontent.com/30348893/74581998-30a42d80-4ff1-11ea-80ac-4fdcff5505ce.png)

 I don't know what's the problem, maybe it didn't successfully connect to the remote repositories? Or are there any other ways to start the jobs?

Also, I found that there some missing plugins like [boostrap4-api-plugin](https://github.com/jenkinsci/bootstrap4-api-plugin) or [plugin-util-api-plugin](https://github.com/jenkinsci/plugin-util-api-plugin) in [_clone.sh](https://github.com/uhafner/warnings-ng-plugin-devenv/blob/master/_clone.sh). These plugins are in [go.sh](https://github.com/uhafner/warnings-ng-plugin-devenv/blob/master/go.sh) and I have to manually clone the plugins in order to deploy the warnings-ng-plugin and analysis-model-plugin successfully, or it will trigger the Jenkins missing instance exception. Are they necessary to the whole project, I can make a PR to help complete them in _clone.sh.

**Comment by uhafner** [comment]
> I don't know what's the problem, maybe it didn't successfully connect to the remote repositories? Or are there any other ways to start the jobs?

Actually, you need to login to Jenkins. Maybe that part needs to be updated in the README. Username and Password are admin.

**Comment by uhafner** [comment]
> Also, I found that there some missing plugins like boostrap4-api-plugin or plugin-util-api-plugin in _clone.sh. These plugins are in go.sh and I have to manually clone the plugins in order to deploy the warnings-ng-plugin and analysis-model-plugin successfully, or it will trigger the Jenkins missing instance exception. Are they necessary to the whole project, I can make a PR to help complete them in _clone.sh.

Ah, this is currently broken due to the split of the plugin into several modules. The idea is that you only need to change or edit the plugin analysis-model, warnings, and the forensics. The other plugins that are part of go.sh should be downloaded from the update manager. (I think I need to enable the experimental updates here.)

**Comment by XiongKezhi** [comment]
Thank you so much! I can finally start debugging now.
