### ISSUE TITLE
Error when running jenkins.sh script

### ISSUE THREAD

**Issue by guptaricha98** [uhafner/warnings-ng-plugin-devenv#8]
Trying to setup dev environment and I am getting below error when running jenkins.sh script,

**jenkins-master_1  | touch: cannot touch '/var/jenkins_home/copy_reference_file.log': Permission denied
jenkins-master_1  | Can not write to /var/jenkins_home/copy_reference_file.log. Wrong volume permissions?
jenkins-master_1  | touch: cannot touch '/var/jenkins_home/copy_reference_file.log': Permission denied
jenkins-master_1  | Can not write to /var/jenkins_home/copy_reference_file.log. Wrong volume permissions?
warnings-ng-plugin-devenv_jenkins-master_1 exited with code 1
jenkins-master_1  | touch: cannot touch '/var/jenkins_home/copy_reference_file.log': Permission denied
jenkins-master_1  | Can not write to /var/jenkins_home/copy_reference_file.log. Wrong volume permissions?**

Please help me fix this error. 
Thanks!

**Comment by XiongKezhi** [comment]
check the write permission for the mounted volumes, maybe docker doesn't have the write permission?

**Comment by uhafner** [comment]
On which OS are you working? How did you install docker?

**Comment by guptaricha98** [comment]
I am working on Windows 10 Home and using Docker Toolbox to run docker on my machines. I installed Docker Toolbox via chocolatey software.

**Comment by uhafner** [comment]
Can you please retry by using [Docker desktop](https://www.docker.com/products/docker-desktop)? I cannot reproduce the problem.
