### ISSUE TITLE
Cannot resolve edu.hm.hafner:analysis-model:test-jar

### ISSUE THREAD

**Issue by Brunochris13** [uhafner/warnings-ng-plugin-devenv#9]
I just added some more keywords to the pattern in NagFortranParser.java.
warnings-ng-plugin-devenv/analysis-model/src/main/java/edu/hm/hafner/analysis/parser/NagFortranParser.java

I wanted to test them, so I've only done the steps with first steps of README.md file. (Cloning the repositories and isntalling IntelliJ) I did not install Docker, Jenkins, since I did not want to test the UI or anything further. What I wanted to test was the file 
warnings-ng-plugin-devenv/analysis-model/src/test/java/edu/hm/hafner/analysis/parser/NagFortranParserTest.java

I created a JUnit Run Configuration to just run this test file, but I get this error message.
`java: package edu.hm.hafner.analysis.assertions does not exist`

I am guessing that package should have come from Maven, but Maven has this error message
`Cannot resolve edu.hm.hafner:analysis-model:test-jar`

I am on Windows.

Can you please help me? If you need any more information please let me know.

**Comment by uhafner** [comment]
Do you have maven installed locally? You can simple `cd`  to the analysis-model module and run there `man verify` in the terminal, does that work?

**Comment by Brunochris13** [comment]
I installed Maven and ran mvn verify. This is the Error message I got

[ERROR] Failed to execute goal on project analysis-model: Could not resolve dependencies for project edu.hm.hafner:analysis-model:jar:9.4.0-SNAPSHOT: Failure to find edu.hm.hafner:analysis-model:jar:test-jar in https://repo.jenkins-ci.org/public/ was cached in the local repository, resolution will not be reattempted until the update interval of repo.jenkins-ci.org has elapsed or updates are forced -> [Help 1]

**Comment by uhafner** [comment]
In which module did you run the command? cd to analysis-model and then run `mvn install`.

**Comment by Brunochris13** [comment]
I ran the command in analysis-model.

This the error message I got when I ran `mvn install` in analysis-model.

[ERROR] Failed to execute goal on project analysis-model: Could not resolve dependencies for project edu.hm.hafner:analysis-model:jar:9.4.0-SNAPSHOT: Could not find artifact edu.hm.hafner:analysis-model:jar:test-jar in repo.jenkins-ci.org (https://repo.jenkins-ci.org/public/) -> [Help 1]

**Comment by uhafner** [comment]
I updated the configuration of the project. Can you please retry?

**Comment by Brunochris13** [comment]
It works now. I also had another problem afterwards, but it was because I was using a newer version of Java (15.1), when I changed back to Java 8 evertying worked. Thank you.
